server:
  port: 8085

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://mysql-appointment-db:3306/veterinary_appointment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      patient-service:
        connectTimeout: 5000
        readTimeout: 5000
      user-service:
        connectTimeout: 5000
        readTimeout: 5000

jwt:
  secret: VeterinaryClinicSecretKey2024!@#$%^&*()

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.veterinary.appointment: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    feign: DEBUG